//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool_Wpf_DevExpress.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostoGiornalieroEncodedEquipment
    {
        public System.DateTime CheckDate { get; set; }
        public decimal DailyCost { get; set; }
        public int DailyProducedPcs { get; set; }
    }
}
