//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool_Wpf_DevExpress.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tools
    {
        public string IdTool { get; set; }
        public string BoschCode { get; set; }
        public string Description { get; set; }
        public string PrimarySupplier { get; set; }
        public string SecondarySupplier { get; set; }
        public string PrimarySharpener { get; set; }
        public string SecondarySharpener { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string TurretCode { get; set; }
        public string PresettingQuoteNGEM1 { get; set; }
        public string PresettingQuoteNGEM2 { get; set; }
        public string PresettingDiameter { get; set; }
        public string Presetting { get; set; }
        public Nullable<int> Life { get; set; }
        public string SProposal { get; set; }
        public string FProposal { get; set; }
        public string SValue { get; set; }
        public string FValue { get; set; }
        public string Refrigeration { get; set; }
        public string Accessories { get; set; }
    
        public virtual Tools Tools1 { get; set; }
        public virtual Tools Tools2 { get; set; }
    }
}
